name: Sample App

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_call:

permissions: read-all

env:
  ORG_GRADLE_PROJECT_openrtbUsername: ${{ github.actor }}
  ORG_GRADLE_PROJECT_openrtbPassword: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
         lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

      - name: Upload Nimbus Sample App
        uses: actions/upload-artifact@v4
        with:
          name: nimbus-android-sample
          path: app/build/outputs/apk/
          retention-days: 5
