name: Sample App Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - main

permissions: read-all

env:
  ORG_GRADLE_PROJECT_openrtbUsername: ${{ github.actor }}
  ORG_GRADLE_PROJECT_openrtbPassword: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         lfs: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
