name: Sample App

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_call:

permissions: read-all

env:
  ORG_GRADLE_PROJECT_openrtbUsername: ${{ github.actor }}
  ORG_GRADLE_PROJECT_openrtbPassword: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build
        run: ./gradlew build

      - name: Upload Nimbus Sample App
        uses: actions/upload-artifact@v4
        with:
          name: nimbus-android-sample
          path: app/build/outputs/
          retention-days: 5

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: '**/build/reports/'
