name: Internal App

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      build_notes:
        description: "A description of what this build contains"
        required: true
        type: string

permissions: read-all

env:
  ORG_GRADLE_PROJECT_openrtbUsername: ${{ github.actor }}
  ORG_GRADLE_PROJECT_openrtbPassword: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Internal code
        uses: actions/checkout@v4
        with:
          repository: 'adsbynimbus/nimbus-android'
          path: 'nimbus-android'
          ssh-key: ${{ secrets.NIMBUS_ANDROID_KEY }}
          lfs: true

      - name: Checkout Sample code
        uses: actions/checkout@v4
        with:
          path: 'nimbus-android/sample'
          lfs: true

      - name: Checkout Nimbus Android Extensions
        uses: actions/checkout@v4
        with:
          repository: 'adsbynimbus/nimbus-android-extensions'
          path: 'nimbus-android-extensions'
          ssh-key: ${{ secrets.EXTENSIONS_DEPLOY_KEY }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build App
        run: ./gradlew :app:build
        working-directory: nimbus-android

      - name: Upload to Firebase
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          ORG_GRADLE_PROJECT_firebaseAppId: ${{ secrets.FIREBASE_APP_ID }}
          ORG_GRADLE_PROJECT_releaseDescription: ${{ inputs.build_notes }}
        run: |
          echo ${{ secrets.FIREBASE_DEPLOY_JSON }} | base64 --decode > ./firebase.json
          ./gradlew appDistributionUploadDebug
        working-directory: nimbus-android
