name: Build Apps

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  sample:
    name: Build Sample App
    uses: ./.github/workflows/build.yml

  internal:
    name: Build Internal App
    if: ${{ !startsWith(github.head_ref, 'arch') }}
    uses: ./.github/workflows/internal.yml
    secrets: inherit

  test:
    name: UI Test
    needs: sample
    runs-on: ubuntu-latest
    steps:
      - name: Download Release
        uses: actions/download-artifact@v3

      - name: Checkout Nimbus Mobile QA
        uses: actions/checkout@v3
        with:
          repository: 'timehop/nimbus-mobile-qa'
          path: .maestro
          ref: build/flow
          ssh-key: ${{ secrets.NIMBUS_QA_DEPLOY }}

      - name: Run Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD }}
          app-file: app/build/outputs/apk/release/app-release-unsigned.apk
          env: |
            APP_ID=com.adsbynimbus.android.sample
